# Buses
sql.bus.find_all=SELECT bus_id, license_plate, model, seat_capacity FROM buses
sql.bus.insert=INSERT INTO buses (license_plate, model, seat_capacity) VALUES (?, ?, ?)
sql.bus.update=UPDATE buses SET license_plate = ?, model = ?, seat_capacity = ? WHERE bus_id = ?
sql.bus.delete=DELETE FROM buses WHERE bus_id = ?